language: java

before_install:
    - git clone https://github.com/jeddict/netbeans-modeler.git ~/builds/netbeans-modeler
    - pushd ~/builds/netbeans-modeler
    - mvn clean install
    - popd